_BASE_: ./Base-bagtricks.yml

MODEL:
  WEIGHTS: "/home/aistudio/my_project/YOLO_Bicycle_Theft_Detection/src/models/weights/market_bot_R50-ibn.pth"
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("BikePerson",)
  TESTS: ("BikePerson",)

OUTPUT_DIR: logs/market1501/bagtricks_R50-ibn
